## ** Numpy for Linear Algebra **

In [1]:
import numpy as np
import pandas as pd

### np.full()

- np.full(shape, fill_value, dtype=None, order='C', *, like=None)
- Return a new array of given shape and type, filled with `fill_value`.

In [2]:
np.full((2,3),5,dtype=int)

array([[5, 5, 5],
       [5, 5, 5]])

In [3]:
np.full((2,3),23,dtype=float)

array([[23., 23., 23.],
       [23., 23., 23.]])

### np.ones()

- np.ones(shape, dtype=None, order='C', *, like=None)
- Return a new array of given shape and type, filled with ones.

In [4]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

### np.zeros()

- np.zeros(shape, dtype=float, order='C', *, like=None)
- Return a new array of given shape and type, filled with zeros.

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### np.random()

- using random matrix 
- Return random floats in the half-open interval [0.0, 1.0)

In [6]:
x=np.random.random((3,4))
x

array([[0.50926474, 0.2908125 , 0.76181099, 0.81197574],
       [0.94241128, 0.80620503, 0.98220716, 0.17292132],
       [0.29355934, 0.5062139 , 0.505177  , 0.71247425]])

In [7]:
x.dtype

dtype('float64')

### Matrix Addition

In [8]:
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
B=np.array([[2,3,4],[6,7,8]])
B

array([[2, 3, 4],
       [6, 7, 8]])

In [10]:
C=A+B
C

array([[ 3,  5,  7],
       [10, 12, 14]])

In [11]:
np.add(A,B, dtype=int)

array([[ 3,  5,  7],
       [10, 12, 14]])

### Matrix Subtraction

In [12]:
C1=B-A
C1

array([[1, 1, 1],
       [2, 2, 2]])

In [13]:
np.subtract(B,A,dtype=int)

array([[1, 1, 1],
       [2, 2, 2]])

### Matrix Multiplication (Elementwise)

In [14]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
B

array([[2, 3, 4],
       [6, 7, 8]])

In [16]:
C2=A*B
C2

array([[ 2,  6, 12],
       [24, 35, 48]])

In [17]:
np.multiply(A,B,dtype=int)

array([[ 2,  6, 12],
       [24, 35, 48]])

### Matrix Division (Elementwise)

In [18]:
C=A/B
C

array([[0.5       , 0.66666667, 0.75      ],
       [0.66666667, 0.71428571, 0.75      ]])

In [19]:
np.divide(A,B)

array([[0.5       , 0.66666667, 0.75      ],
       [0.66666667, 0.71428571, 0.75      ]])

### Matrix Products

In [20]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
A.shape

(2, 3)

In [22]:
B

array([[2, 3, 4],
       [6, 7, 8]])

In [23]:
B.shape

(2, 3)

In [24]:
## tranpose

In [25]:
B.T

array([[2, 6],
       [3, 7],
       [4, 8]])

In [26]:
B.T.shape

(3, 2)

In [27]:
## no of columns of A must be same as rows of B for matrix product

In [28]:
np.matmul(A,B.T)

array([[ 20,  44],
       [ 47, 107]])

### Dot Product

In [29]:
np.dot(A.T,B)

array([[26, 31, 36],
       [34, 41, 48],
       [42, 51, 60]])

In [30]:
np.dot(A,B.T)

array([[ 20,  44],
       [ 47, 107]])

### np.linalg -- Linear Algebra module

- np.linalg.matrix_power(a, n)
- Raise a square matrix to the (integer) power `n`


In [31]:
A=np.array([[1,2,3],[4,5,6],[6,7,8]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [32]:
A.shape

(3, 3)

In [33]:
np.linalg.matrix_power(A,2)  # A*A matrix product

array([[ 27,  33,  39],
       [ 60,  75,  90],
       [ 82, 103, 124]])

In [34]:
np.matmul(A,A)

array([[ 27,  33,  39],
       [ 60,  75,  90],
       [ 82, 103, 124]])

### np.kron()

- Kronecker product of two arrays.

- Computes the Kronecker product, a composite array made of blocks of the second array scaled by the first.

In [35]:
np.kron(A,B)

array([[ 2,  3,  4,  4,  6,  8,  6,  9, 12],
       [ 6,  7,  8, 12, 14, 16, 18, 21, 24],
       [ 8, 12, 16, 10, 15, 20, 12, 18, 24],
       [24, 28, 32, 30, 35, 40, 36, 42, 48],
       [12, 18, 24, 14, 21, 28, 16, 24, 32],
       [36, 42, 48, 42, 49, 56, 48, 56, 64]])

## Matrix Decompositions

### 1) Cholesky Decomposition $$A=UU^H $$

In [36]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

### np.linalg.cholesky(a)

- Return the Cholesky decomposition, `L * L.H`, of the square matrix `a`,where `L` is lower-triangular and .H is the conjugate transpose operator (which is the ordinary transpose if `a` is real-valued)

### 2) QR Decomposition $$ A=QR$$

### np.linalg.qr(a, mode='reduced')

- Compute the qr factorization of a matrix.

- Factor the matrix `a` as *qr*, where `q` is orthonormal and `r` is upper-triangular.

In [37]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [38]:
np.linalg.qr(A)

(array([[-0.13736056,  0.93587869,  0.32444284],
        [-0.54944226,  0.20054543, -0.81110711],
        [-0.82416338, -0.28967674,  0.48666426]]),
 array([[-7.28010989e+00, -8.79107609e+00, -1.03020423e+01],
        [ 0.00000000e+00,  8.46747384e-01,  1.69349477e+00],
        [ 0.00000000e+00,  0.00000000e+00,  8.88178420e-16]]))

In [39]:
Q=np.linalg.qr(A)[0]
Q

array([[-0.13736056,  0.93587869,  0.32444284],
       [-0.54944226,  0.20054543, -0.81110711],
       [-0.82416338, -0.28967674,  0.48666426]])

In [40]:
R=np.linalg.qr(A)[1]
R

array([[-7.28010989e+00, -8.79107609e+00, -1.03020423e+01],
       [ 0.00000000e+00,  8.46747384e-01,  1.69349477e+00],
       [ 0.00000000e+00,  0.00000000e+00,  8.88178420e-16]])

In [41]:
A1=np.matmul(Q,R)
A1

array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]])

### 3) Eigen value decompostion (EVD)  $$ A=PDP^{-1}$$

### np.linalg.eig(a)

- Compute the eigenvalues and right eigenvectors of a square array.

In [42]:
np.linalg.eig(A)

(array([ 1.50000000e+01, -1.00000000e+00,  4.65763037e-17]),
 array([[ 2.49206599e-01,  8.32050294e-01,  4.08248290e-01],
        [ 5.69615084e-01, -4.59516133e-16, -8.16496581e-01],
        [ 7.83220740e-01, -5.54700196e-01,  4.08248290e-01]]))

In [43]:
D=np.linalg.eig(A)[0]
P=np.linalg.eig(A)[1]

In [44]:
D

array([ 1.50000000e+01, -1.00000000e+00,  4.65763037e-17])

In [45]:
P

array([[ 2.49206599e-01,  8.32050294e-01,  4.08248290e-01],
       [ 5.69615084e-01, -4.59516133e-16, -8.16496581e-01],
       [ 7.83220740e-01, -5.54700196e-01,  4.08248290e-01]])

In [46]:
## Another method 

In [47]:
D,P=np.linalg.eig(A)

In [48]:
D

array([ 1.50000000e+01, -1.00000000e+00,  4.65763037e-17])

In [49]:
P

array([[ 2.49206599e-01,  8.32050294e-01,  4.08248290e-01],
       [ 5.69615084e-01, -4.59516133e-16, -8.16496581e-01],
       [ 7.83220740e-01, -5.54700196e-01,  4.08248290e-01]])

### np.diag(v, k=0)

- Extract a diagonal or construct a diagonal array.

In [50]:
D=np.diag(D)
D

array([[ 1.50000000e+01,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  4.65763037e-17]])

In [51]:
## first find product of matrix P & diagonal matrix D

In [52]:
P_D=np.matmul(P,D)
P_D

array([[ 3.73809899e+00, -8.32050294e-01,  1.90146964e-17],
       [ 8.54422625e+00,  4.59516133e-16, -3.80293927e-17],
       [ 1.17483111e+01,  5.54700196e-01,  1.90146964e-17]])

In [53]:
## Find inverse of matrix P

### np.linalg.inv(a)

- Compute the (multiplicative) inverse of a matrix.

In [54]:
P_inverse=np.linalg.inv(P)
P_inverse

array([[ 0.4681524 ,  0.5851905 ,  0.7022286 ],
       [ 0.90138782,  0.22534695, -0.45069391],
       [ 0.32659863, -0.81649658,  0.48989795]])

In [55]:
## Now find decomposition 

In [56]:
A=np.matmul(P_D,P_inverse)
A

array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]])

### np.linalg.eigvals(a)

- Compute the eigenvalues of a general matrix.


In [57]:
np.linalg.eigvals(A)

array([ 1.50000000e+01, -1.00000000e+00, -1.85979816e-16])

### 4) Singular value decomposition (SVD)     $$ A=USV^T$$

### np.linalg.svd(a)

- np.linalg.svd(a, full_matrices=True, compute_uv=True, hermitian=False)
- Singular Value Decomposition.

In [58]:
np.linalg.svd(A)

(array([[-0.23498172,  0.91625348,  0.32444284],
        [-0.56747984,  0.14167532, -0.81110711],
        [-0.78914525, -0.37471012,  0.48666426]]),
 array([1.54611193e+01, 9.76621976e-01, 6.88637940e-16]),
 array([[-0.46825669, -0.57119923, -0.67414176],
        [-0.78362555, -0.08405223,  0.6155211 ],
        [ 0.40824829, -0.81649658,  0.40824829]]))

In [59]:
U,S,V=np.linalg.svd(A)

In [60]:
U

array([[-0.23498172,  0.91625348,  0.32444284],
       [-0.56747984,  0.14167532, -0.81110711],
       [-0.78914525, -0.37471012,  0.48666426]])

In [61]:
S

array([1.54611193e+01, 9.76621976e-01, 6.88637940e-16])

In [62]:
V

array([[-0.46825669, -0.57119923, -0.67414176],
       [-0.78362555, -0.08405223,  0.6155211 ],
       [ 0.40824829, -0.81649658,  0.40824829]])

## Matrix norms

### np.linalg.norm(x)

- np.linalg.norm(x, ord=None, axis=None, keepdims=False)
- Matrix or vector norm.

In [63]:
np.linalg.norm(A)

15.491933384829682

### np.linalg.cond(x, p=None)

- Compute the condition number of a matrix.

In [64]:
np.linalg.cond(A)

2.245173897190977e+16

### np.linalg.det(a)

- Compute the determinant of an array.

In [65]:
np.linalg.det(A)

0.0

### np.linalg.matrix_rank(A)

- np.linalg.matrix_rank(A, tol=None, hermitian=False)
- Return matrix rank of array using SVD method

In [66]:
np.linalg.matrix_rank(A)

2

### np.trace(a)

- np.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
- Return the sum along diagonals of the array.

In [67]:
np.trace(A)

14.000000000000014

## Solving equations

$$AX=b$$

In [68]:
A=np.array([[1,2,4],[5,2,3],[6,4,2]])
A

array([[1, 2, 4],
       [5, 2, 3],
       [6, 4, 2]])

In [69]:
b=np.random.random((3,1))
b

array([[0.01596324],
       [0.13582002],
       [0.53336466]])

In [70]:
## Method 1   

$$ x=A^{-1}b$$

In [71]:
A_inverse=np.linalg.inv(A)
A_inverse

array([[-0.2  ,  0.3  , -0.05 ],
       [ 0.2  , -0.55 ,  0.425],
       [ 0.2  ,  0.2  , -0.2  ]])

In [72]:
x=np.matmul(A_inverse,b)
x

array([[ 0.01088512],
       [ 0.15517162],
       [-0.07631628]])

In [73]:
## using solve function

### np.linalg.solve(a, b)

- Solve a linear matrix equation, or system of linear scalar equations.

In [74]:
x=np.linalg.solve(A,b)
x

array([[ 0.01088512],
       [ 0.15517162],
       [-0.07631628]])